/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cieo233_notetest_OpenCVHelper */

#ifndef _Included_com_example_cieo233_notetest_OpenCVHelper
#define _Included_com_example_cieo233_notetest_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cieo233_notetest_OpenCVHelper
 * Method:    Checkedge
 * Signature: ([III)[I
 */
JNIEXPORT void JNICALL Java_com_example_cieo233_notetest_OpenCVHelper_Checkedge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     com_example_cieo233_notetest_OpenCVHelper
 * Method:    Cut
 * Signature: ([III[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_cieo233_notetest_OpenCVHelper_Cut
  (JNIEnv *, jclass, jintArray,jintArray, jint, jint,jintArray);

#ifdef __cplusplus
}
#endif
#endif
